- .gitignore
- .pre-commit-config.yaml
- README.md
- setup.cfg
- yt_idefix/__init__.py
- yt_idefix/_io/commons.py
- yt_idefix/_io/dmp_io.py
- yt_idefix/_io/vtk_io.py
- yt_idefix/api.py
- yt_idefix/data_structures.py
- yt_idefix/fields.py
- yt_idefix/io.py
- yt_idefix/tests/test_dev.py
> ENH: sketch a class hierarchy to make room for vtk compat

- README.md
- setup.cfg
- yt_idefix/__init__.py
- yt_idefix/_io/commons.py
- yt_idefix/_io/dmp_io.py
- yt_idefix/_io/vtk_io.py
- yt_idefix/api.py
- yt_idefix/data_structures.py
- yt_idefix/fields.py
- yt_idefix/io.py
> ENH: add provisional support for vtk data

- README.md
- tests/test_vtk.py
- yt_idefix/__init__.py
- yt_idefix/_io/commons.py
- yt_idefix/api.py
- yt_idefix/loaders.py
> ENH: add custom loader functions

- .github/workflows/bleeding-edge.yaml
- pyproject.toml
- tests/test_dmp.py
- tests/test_vtk.py
This is a first pass at fixing known incompatibilities with yt 4.1dev0, it's necessary but not sufficient
> ENH: improve compatibility with yt 4.1.dev0

- setup.cfg
- tests/test_vtk.py
- yt_idefix/__init__.py
- yt_idefix/io.py
- fixes #67 
- adds test for derived field
> BUG: fix chunk index problem

- tests/data/pluto_sedov/meta.yaml
- tests/data/pluto_sod/meta.yaml
- tests/test_vtk.py
- yt_idefix/data_structures.py
- yt_idefix/definitions.py
- enable to derive all default_units with the units passed to `units_override`
- adds test for `units_override`
> ENH: enable to override all default_units with units_override (Pluto)

- tests/test_loading.py
- yt_idefix/data_structures.py
fix #91
I may hold on to this for a couple days so I can get #90 in and release them together.
> BUG: fix loading PlutoVtkDataset from parent dir

- yt_idefix/data_structures.py
This needs to be validated against the bleeding-edge workflow: https://github.com/neutrinoceros/yt_idefix/actions/runs/1845525135
> ENH: fix a deprecation from yt dev branch

- setup.cfg
- yt_idefix/__init__.py
- yt_idefix/_io/dmp_io.py
> BUG: fix compatibility for single precision Idefix dump files

- .github/workflows/cd.yml
- .github/workflows/ci.yml
- .github/workflows/type-checking.yaml
- .pre-commit-config.yaml
- MNT: upgrade github actions
- MNT: add a pre-commit hook
> MNT: upgrade GHA an pre-commit

- yt_idefix/data_structures.py
> BUG: fix AMR level declaration

- .github/workflows/bleeding-edge.yaml
- .github/workflows/ci.yml
- pyproject.toml
- TST: ignore out-of-reach pending deprecation warning
- TST: enable colored logs for pytest on GHA
> TST: housekeeping

- tests/test_vtk.py
- yt_idefix/data_structures.py
This is in preparation for #167
> ENH: automatic discovery and parsing for pluto.ini, idefix.ini, definitions.h and definitions.hpp

- yt_idefix/data_structures.py
> TYP: resolve unchecked annotations

- tests/data/pluto_disk_planet/definitions.h
- yt_idefix/data_structures.py
> ENH: resolve the variables in unit definitions (PLUTO)

- yt_idefix/data_structures.py
It doesn't do anything anymore, might as well through it out.
> MNT: cleanup noop code

- .github/workflows/bleeding-edge.yaml
- README.md
- pyproject.toml
> REL: fix release 0.16

- yt_idefix/data_structures.py
fix deprecation warnings for Dataset.geometry being parsed as a pure string
> BUG: fix future incompatibility with yt 4.2

- pyproject.toml
- yt_idefix/__init__.py
- yt_idefix/_io/commons.py
- yt_idefix/_io/dmp_io.py
> BUG: add support for boolean fields in dump files

- tests/data/pluto_sedov/meta.yaml
I noticed we lack a case to test the value of a given current time.
> TST: Improve current time test

- tests/data/pluto_sedov/meta.yaml
- tests/data/pluto_sod/definitions.h
- tests/data/pluto_sod/meta.yaml
- yt_idefix/data_structures.py
Trying to replay PRs #206 and #208 from @xshaokun without the git-lfs error from #206
I will exceptionally need to delete commits from the main branch, and merge this to replace the lacking history
> Replay PRs #206 and #208

- .gitattributes
> MNT: track *.h5 files with git-lfs

- yt_idefix/_backports.py
> ENH: implement portable replacements for str.removeprefix and str.removesufix

- tests/conftest.py
- tests/data/FargoMHDSpherical/meta.yaml
- tests/data/cataclysmic-disk/meta.yaml
- tests/data/khi/meta.yaml
- tests/data/pluto_disk_planet/meta.yaml
- tests/data/pluto_rotor/meta.yaml
- tests/data/pluto_sedov/meta.yaml
- tests/data/pluto_sod/meta.yaml
> TST: refactor test infra to make room for new data formats

- tests/conftest.py
> TST: fix a broken error message in conftest.py

- tests/conftest.py
Another mistake I made in #221
> TST: fix a broken type hint in conftest.py

- tests/conftest.py
based off, and in support of #209
> TST: add test infra for XDMF data

- tests/test_vtk.py
- yt_idefix/data_structures.py
This makes for a better fundation to later include #209 with much less code duplication
> RFC: reorganize class hierarchy to make room for new dataformats

- yt_idefix/data_structures.py
a small refactor in support to #209
> RFC: revamp GoodBoyDataset._parse_code_version

- yt_idefix/data_structures.py
In support to #209, moving this method up the class hierarchy so it can be inherited.
> RFC: move _set_code_unit_attributes from PlutoVtkDataset to StaticPlutoDataset

- yt_idefix/data_structures.py
still in support to #209, follow up to #230
> RFC: more more of PlutoVtkDataset's logic to super class

- yt_idefix/data_structures.py
in support to #209
currently this is in a broken state, I need to wrap my head around multiple inheritance
> RFC: move and simplify current_time parsing for pluto datasets

- .github/workflows/ci.yml
- .gitignore
- pyproject.toml
- tests/test_xdmf.py
- yt_idefix/_io/commons.py
- yt_idefix/_io/h5_io.py
- yt_idefix/_io/vtk_io.py
- yt_idefix/api.py
- yt_idefix/data_structures.py
- yt_idefix/fields.py
- yt_idefix/io.py
As discussed in the previous PR #202 
This is a new branch xdmf that can be merged!
> PLUTO xdmf dump support

- README.md
> DOC: assemble support information in a table

- README.md
As this frontend has more and more features and optional parameters, I'm going to update the section `usage` of our doc :)
This PR will close #247
> DOC: document supported additional arguments to `yt.load`

- README.md
- pyproject.toml
- src/yt_idefix/data_structures.py
- tests/test_dmp.py
I'll wait until yt 4.2.x cools down a little bit before I merge this
> BLD: drop support for yt 4.1.x

- src/yt_idefix/_io/vtk_io.py
> UX: emit a warning when reading invalid coordinate data from vtk files

- README.md
Minor correction of quote type in documentation.
> [DOC] Minor correction in documentation

- src/yt_idefix/_io/dmp_io.py
- src/yt_idefix/io.py
opening with a preliminary implementation (support isn't actually added yet, I'm just throwing in the structure).
I need to fix type-checking as well as any failing tests before I move forward.
> ENH: add support for big-endian dumps data

- pyproject.toml
- src/yt_idefix/_io/dmp_io.py
- src/yt_idefix/data_structures.py
- tests/test_vtk.py
also fix an unreleased bug from #285
> STY: lint unused function arguments

- .pre-commit-config.yaml
- README.md
- STY: upgrade black to 23.9.1
- DOC: makeover
> DOC: makeover

- src/yt_idefix/data_structures.py
Currently this doesn't do anything since inifix is a hard dependency, but it might become useful in the future if this is merged in mainline yt
> ENH: implement Dataset._load_requirements

- .pre-commit-config.yaml
- README.md
- pyproject.toml
- src/yt_idefix/_io/dmp_io.py
- src/yt_idefix/_io/vtk_io.py
- **MNT: migrate from black+blacken-docs to ruff-format**
- **STY: stylistic changes from ruff-format**
- **MNT: migrate ruff config**
> MNT: migrate from black to ruff-format

- .github/workflows/bleeding-edge.yaml
- .github/workflows/ci.yml
- pyproject.toml
> TST: migrate to official astral-sh/setup-uv action

- src/yt_idefix/_io/commons.py
Reverts neutrinoceros/yt_idefix#333
> Revert "BUG: fix native coordinate parsing for azimuthal-normal spherical slices"

- src/yt_idefix/io.py
Close #356
Close #357 (which this is an alternative to)
> BUG: fix incorrect regexp subject (only match basenames, not entire paths)

- .github/workflows/bleeding-edge.yaml
> TST: drop actions/setup-python action
