setup.cfg
yt_idefix/__init__.py
yt_idefix/_io/dmp_io.py

got a ~25% speedup for a ProjectionPlot example using a 660MiB dataset.
Only problem is that the reshaping is currently broken so the results are incorrect.
fix #17

ENH: improve reading perfs for dmp files

---

.github/workflows/cd.yml
.pre-commit-config.yaml
README.md
pyproject.toml
setup.cfg
yt_idefix/__init__.py
yt_idefix/_io/dmp_io.py
yt_idefix/_io/vtk_io.py
yt_idefix/data_structures.py

motivation: unlock dataclasses

MNT: drop support for Python 3.6

---

setup.cfg
yt_idefix/__init__.py
yt_idefix/data_structures.py

- ENH: treat ytLogger as external (don't import it from yt.funcs)
- BUG: always set current_time as a unyt_quantity object, not a float
- ENH: lift version upper limits in dependencies
- REL: bump version number to 0.9.0

REL: prep for release 0.9

---

.github/workflows/ci.yml
.pre-commit-config.yaml
README.md
pyproject.toml
setup.cfg
tests/conftest.py
tests/test_vtk.py
yt_idefix/__init__.py
yt_idefix/loaders.py

Opening as a draft (yt 4.0.2 isn't out yet, so this will fail CI at first)

DEPR: deprecate yt_idefix.load, update requirements

---

setup.cfg
tests/test_vtk.py
yt_idefix/__init__.py
yt_idefix/_io/commons.py
yt_idefix/_io/dmp_io.py
yt_idefix/_io/vtk_io.py
yt_idefix/data_structures.py
yt_idefix/loaders.py

This is supposed to be a simple refactor with no changes but I found that it breaks some PLUTO tests where we call `yt_idefix.load()` without a `geometry` argument, though I think the geometry is _supposed_ to be automatically parsed from `definitions.h`.
@xshaokun, I'd like your feedback on this if you can. I think it's a bug that pre-exists and I'm just making it apparent, can you confirm/infirm ?

RFC: disantangle metadata parsing for vtk files, centralize geometry validation

---

setup.cfg
yt_idefix/__init__.py
yt_idefix/loaders.py

I now think #86 is really a regression upstream (I probably broke one of yt's pixelizers in between 4.0.1 and 4.0.2), so I'm restoring compatibility with 4.0.1
this should close #86, and I'll need to report/patch this upstream
I don't want to backpedal #73 completely so I won't be _testing_ against yt 4.0.1 anymore, if I can avoid it.

MNT: reallow compat with yt 4.0.1

---

yt_idefix/data_structures.py

The setup of nuclei density fields can be activated by setting `default_species_fields="ionized"`. The derived fields `H_nuclei_density` and `El_number_density` are useful, for example, in emission plotting.
So I intended to add a keyword parameter `default_species_fields` in our frontend.

ENH: enable to set default_species_fields

---

yt_idefix/_typing.py
yt_idefix/data_structures.py

requesting a quick review from @xshaokun 
Can you please tell me if there's any other valid value to the `default_species_fields` argument besides `"ionized"` and `None` ?

BUG: fix IdefixDataset.__init__ signature for compatibility with parent class

---

tests/conftest.py
tests/data/FargoMHDSpherical/meta.yaml
tests/data/cataclysmic-disk/meta.yaml
tests/data/khi/meta.yaml
tests/data/pluto_disk_planet/meta.yaml
tests/data/pluto_rotor/meta.yaml
tests/data/pluto_sedov/meta.yaml
tests/data/pluto_sod/meta.yaml
tests/test_vtk.py
yt_idefix/data_structures.py

The behavior of this bug can be shown by the following code:
``` Python
ds = yt.load("tests/data/pluto_disk_planet/data.0010.vtk")
print("current_time: ", ds.current_time)
print("current_time_cgs: ", ds.current_time.in_cgs())
print("time_unit: ", ds.time_unit)
codet = ds.quan(1, "code_time")
print("code_time", ds.unit_registry["code_time"])
print("codet: ", codet)
print("codet_cgs: ", codet.in_cgs())
```
The ouput is 
```
current_time:  1.0 code_time
current_time_cgs:  1.0 s
time_unit:  373173289.848891 s
code_time (373173289.848891, (time), 0.0, '\\rm{code\\ time}', False)
codet:  1 code_time
codet_cgs:  1.0 s
```
The reason is our too early calling of "code_time" in the definition of `self.current_time`, which is called before `self.set_units()`. So the conversion factor between …

BUG: fix incorrect conversion between code_time and cgs_unit

---

setup.cfg
yt_idefix/__init__.py
yt_idefix/_io/vtk_io.py

Follow up to https://github.com/neutrinoceros/yt_idefix/pull/27
I honestly can't remember why exactly I thought this shift was a good thing, but it's objectively broken (it produces angles outside of the (0, 2 PI) interval).
This was fine up to yt 4.0.2 but the problem surfaced with yt 4.0.3, with which polar plots are uterly broken. This fixes the problem entirely.

BUG: fix an issue where azimuthal coordinates in polar geometry was incorrectly shifted

---

yt_idefix/data_structures.py

Rationale: this implem won't be needed in yt 4.1 (https://github.com/yt-project/yt/pull/3936)

ENH: make custom __repr__ version specific

---

.pre-commit-config.yaml

for context: https://github.com/macisamuele/language-formatters-pre-commit-hooks/issues/133
I don't value this formatter enough to wait for it to be fixed

MNT: drop broken toml formatter

---

.github/workflows/bleeding-edge.yaml
.github/workflows/ci.yml
README.md
pyproject.toml
tests/requirements.txt
yt_idefix/__init__.py

ENH: define frontend entry points for yt 4.2 (as a beta feature)

---

tests/data/pluto_rotor/meta.yaml
tests/data/pluto_sod/meta.yaml
yt_idefix/data_structures.py

Reminded by the discussion with @dutta-alankar in #202, some bugs need to be fixed.

fix setting code units in PlutoDataset

---

pyproject.toml

I found this more resilient version of inifix is necessary to support some of #209

BLD: require inifix>=4.1.0

---

yt_idefix/data_structures.py
yt_idefix/io.py

This migration is possible now that yt>=4.1 is required

RFC: use Dataset.filename attribute instead of Dataset.parameter_filename (historic alias)

---

yt_idefix/_io/vtk_io.py

Since the stream position was reset in `read_metadata()`, we don't need to reset it again before calling the function.

cleanup: remove redundant stream position reset

---

yt_idefix/_io/vtk_io.py
yt_idefix/data_structures.py

Idefix allows the user to output custom fields in the vtk files and their name is chosen by the user. This means that names containing lower case character may be chosen by the user. Moreover the default vector potential field name also contains a lower case character (_e.g._ `AX1e`)
Currently, for normalisation reasons with different Pluto versions, all native field names are converted to upper case.
This means that such fields can't be accessed via _e.g._ `("idefix-vtk","AX1e")`.
This PR proposes to use this normalisation for Pluto datasets only. This allows the fields to be accessed with the same name they have in the vtk file.

BUG: do not normalise field names to upper case in Idefix vtk

---

tests/test_vtk.py
yt_idefix/data_structures.py

follow up to #245
I would also like to do something about the second warning because it's a problem that it's not possible to silence it.
I'm thinking we should probably just raise a hard error is receiving an invalid `pluto.ini` file, but is it actually invalid to leave units out of it ?
ping @xshaokun for review

UX: rephrase a warning

---

.pre-commit-config.yaml
README.md

This will avoid the introduction of syntax errors in docs (as the ones corrected in #276)

DOC: add blacken-docs to pre-commit toolbelt

---

.github/workflows/bleeding-edge.yaml

Looks like we're only now catching up on deprecation warnings from numpy 1.25, next time I'd like to see them before the release.

TST: use numpy and matplotlib nightlies in bleeding-edge CI

---

.github/workflows/bleeding-edge.yaml

Rationale: we should only care about watching yt, who itself is watching numpy and matplotlib.

TST: stop testing against numpy dev and mpl dev

---

.pre-commit-config.yaml

Formatting first, linting second generates less noise.

MNT: swap order for ruff pre-commit hooks

---

src/yt_idefix/data_structures.py

Idefix vtks don't seem to use a leadin `v` in version numbers anymore.

BUG: fix a spurious UserWarning when loading idefix vtks

---

tests/conftest.py

already patched upstream in https://github.com/h5py/h5py/pull/2416

TST: filter a deprecation warning in numpy via h5py

---

.github/workflows/bleeding-edge.yaml
.github/workflows/ci.yml

Newer versions log which dependencies were built, which is particularily useful in bleeding-edge CI

TST: bump uv (0.2.25 -> 0.4.1)

---

.github/workflows/ci.yml

blocked by yt 4.4.0 (first expected release with cp313 wheels)

TST: add CPython 3.13 to regular CI

---

src/yt_idefix/_io/vtk_io.py

Wait for upstream https://github.com/idefix-code/idefix/pull/292

ENH: prefer native coordinates over reconstructed arrays in vtk files

---

.github/workflows/bleeding-edge.yaml

[example logs](https://github.com/neutrinoceros/yt_idefix/actions/runs/12663389605)
[last succesful run](https://github.com/neutrinoceros/yt_idefix/actions/runs/12637357746/job/35211369047)
the only difference I know of at the moment is that uv was implicitly upgraded from 0.5.14 to 0.5.15, so I'm trying to pin it back to 0.5.14

TST: update uv configuration in bleeding-edge CI

---

src/yt_idefix/_io/vtk_io.py

Fix `read_grid_coordinates()` method so that it returns cell edges when native coordinates are in the metadata.

BUG: fix reading native grid coordinates for idefix 2.2 vtk files

---

uv.lock

```
Updated cmyt v2.0.1 -> v2.0.2
Updated decorator v5.1.1 -> v5.2.1
Updated executing v2.1.0 -> v2.2.0
Updated fonttools v4.55.3 -> v4.56.0
Updated h5py v3.12.1 -> v3.13.0
Updated inifix v5.1.3 -> v6.0.1
Updated ipython v8.31.0 -> v8.34.0
Updated matplotlib v3.10.0 -> v3.10.1
Updated more-itertools v10.5.0 -> v10.6.0
Updated mypy v1.14.1 -> v1.15.0
Updated numpy v2.2.1 -> v2.2.3
Updated pillow v11.0.0 -> v11.1.0
Updated prompt-toolkit v3.0.48 -> v3.0.50
Updated pyaml v24.12.1 -> v25.1.0
Updated pygments v2.18.0 -> v2.19.1
Updated pytest v8.3.4 -> v8.3.5
Updated tomli-w v1.1.0 -> v1.2.0
```

DEP: lock file maintenance
